[package]
name = "meowbot"
version = "0.1.0"
authors = ["Vicfred <vicfred@vicfred.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
