[package]
name = "meowbot"
version = "0.1.0"
authors = ["Vicfred <vicfred@vicfred.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
irc-bot = "0.2.1"
log = "0.4.0"
